#!/bin/sh

zero_or_die()
{
  "$@"
  if [ $? != 0 ]; then
    echo "Failed: $@"
    exit 1
  fi
}

dist="AUTHORS
COPYING
ChangeLog
INSTALL
Makefile.am
Makefile.in
NEWS
README
aclocal.m4
autogen.sh
compile
config.h.in
configure
configure.ac
depcomp
dist
doc/Inconsolata.otf
doc/index.html
install-sh
missing
run_tests
tests/lib
tests/test_backup_name
tests/test_changed
tests/test_dir
tests/test_dir_meta
tests/test_file_body
tests/test_first_backup
tests/test_meta
tests/test_meta2
tests/test_meta3
tests/test_symlink
tests/test_unchanged
tests/test_unchanged2
tests/test_unchanged3
ubtc.c
ubts.c"

mark="VERSION = "
version=`grep "^${mark}" < Makefile | sed -e "s/^${mark}//"`
name="UnnamedBackupTool-${version}"

zero_or_die rm -rf "${name}"
zero_or_die mkdir -p "${name}"

for f in ${dist}
do
  dir="${name}/`dirname ${f}`"
  zero_or_die mkdir -p "${dir}"
  zero_or_die cp -p "${f}" "${dir}"
done

zero_or_die tar cf - "${name}" | zero_or_die xz --compress > "${name}.tar.xz"
zero_or_die rm -rf "${name}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
