#!/bin/sh

if [ "$1" = "-d" ]; then
  sh_opt="-x"
  shift
fi
pattern="test_*"
if [ "$1" != "" ]; then
  pattern="$1"
  shift
fi

mktemp="zero_or_die mktemp -d -t"

dir=$(dirname $0)
tests_dir="${dir}/tests"
export LIB="${tests_dir}/lib"
. "${LIB}"

center="${tests_dir}/center"
"${center}" "=" "Running tests"
summary="summary.log"
zero_or_die rm -f "${summary}"
zero_or_die find tests -type f -name "${pattern}" | while read t
do
  name=$(zero_or_die basename "${t}")
  tmp_dir=$(zero_or_die mktemp -d -t $(zero_or_die basename "${t}"))
  export SRC_DIR="${tmp_dir}/src.test"
  export DEST_DIR="${tmp_dir}/dest.test"
  zero_or_die mkdir -p "${SRC_DIR}" "${DEST_DIR}"
  export CMD="${dir}/src/ubackupme local"
  "${center}" "-" "${t}"
  sh ${sh_opt} "${t}"
  if [ $? -eq 0 ]; then
    result="OK"
  else
    result="NG"
    echo "${t}" >> ${summary}
  fi
  echo "${t}: ${result}"
  zero_or_die rm -rf "${tmp_dir}"
done

"${center}" "=" "Summary"
zero_or_die cat "${summary}" | zero_or_die sort
zero_or_die rm -f "${summary}"

# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2
